{% set version = "4.4-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survey
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survey_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survey/survey_{{ version }}.tar.gz
  sha256: 86400f10e4236f69d2bea63f1f8f0e632bb72caa73469c1f9229a2dc6ad68998

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.12.8
    - r-rcpparmadillo
    - r-lattice
    - r-minqa
    - r-mitools >=2.4
    - r-numderiv
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.12.8
    - r-rcpparmadillo
    - r-lattice
    - r-minqa
    - r-mitools >=2.4
    - r-numderiv
    - r-survival

test:
  commands:
    - $R -e "library('survey')"           # [not win]
    - "\"%R%\" -e \"library('survey')\""  # [win]

about:
  home: http://r-survey.r-forge.r-project.org/survey/
  license: GPL-2.0-or-later
  summary: Summary statistics, two-sample tests, rank tests, generalised linear models, cumulative link models, Cox models, loglinear models, and general maximum pseudolikelihood estimation for multistage stratified, cluster-sampled, unequally weighted survey samples. Variances by Taylor series linearisation or replicate
    weights. Post-stratification, calibration, and raking. Two-phase subsampling designs. Graphics. PPS sampling without replacement. Principal components, factor analysis.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
