{% set version = "3.36" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survey
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survey_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survey/survey_{{ version }}.tar.gz
  sha256: 90f32e9d2b52eacf881e6717a4b5edfc5a3beb5da516f8372293549589d79475

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-lattice
    - r-minqa
    - r-numderiv
    - r-survival
  run:
    - r-base
    - r-matrix
    - r-lattice
    - r-minqa
    - r-numderiv
    - r-survival

test:
  commands:
    - $R -e "library('survey')"           # [not win]
    - "\"%R%\" -e \"library('survey')\""  # [win]

about:
  home: http://r-survey.r-forge.r-project.org/survey/
  license: GPL-2 | GPL-3
  summary: Summary statistics, two-sample tests, rank tests, generalised linear models, cumulative
    link models, Cox models, loglinear models, and general maximum pseudolikelihood
    estimation for multistage stratified, cluster-sampled, unequally weighted survey
    samples. Variances by Taylor series linearisation or replicate weights. Post-stratification,
    calibration, and raking. Two-phase subsampling designs. Graphics. PPS sampling without
    replacement. Principal components, factor analysis.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: survey
# Title: Analysis of Complex Survey Samples
# Description: Summary statistics, two-sample tests, rank tests, generalised linear models, cumulative link models, Cox models, loglinear models, and general maximum pseudolikelihood estimation for multistage stratified, cluster-sampled, unequally weighted survey samples. Variances by Taylor series linearisation or replicate weights. Post-stratification, calibration, and raking. Two-phase subsampling designs. Graphics. PPS sampling without replacement. Principal components, factor analysis.
# Version: 3.35-1
# Author: Thomas Lumley
# Maintainer: "Thomas Lumley" <t.lumley@auckland.ac.nz>
# License: GPL-2 | GPL-3
# Depends: R (>= 3.1.0), grid, methods, Matrix, survival
# Imports: stats, graphics, splines, lattice, minqa, numDeriv
# Suggests: foreign, MASS, KernSmooth, hexbin, mitools, RSQLite, RODBC, quantreg, parallel, CompQuadForm, DBI
# URL: http://r-survey.r-forge.r-project.org/survey/
# NeedsCompilation: no
# Packaged: 2019-01-29 00:44:30 UTC; tlum005
# Repository: CRAN
# Date/Publication: 2019-01-29 09:30:11 UTC
