{% set version = '3.34' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survey
  version: {{ version|replace("-", "_") }}

source:
  fn: survey_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/survey_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survey/survey_{{ version }}.tar.gz
  sha256: c5f8ea6595cf33dbfcf650fca1561338f7d14ee238459dd354aad43571250224

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-lattice
    - r-minqa
    - r-numderiv
    - r-survival
  run:
    - r-base
    - r-matrix
    - r-lattice
    - r-minqa
    - r-numderiv
    - r-survival

test:
  commands:
    - $R -e "library('survey')"           # [not win]
    - "\"%R%\" -e \"library('survey')\""  # [win]

about:
  home: http://r-survey.r-forge.r-project.org/survey/
  license: GPL-2 | GPL-3
  summary: Summary statistics, two-sample tests, rank tests, generalised linear models, cumulative
    link models, Cox models, loglinear models, and general maximum pseudolikelihood
    estimation for multistage stratified, cluster-sampled, unequally weighted survey
    samples. Variances by Taylor series linearisation or replicate weights. Post-stratification,
    calibration, and raking. Two-phase subsampling designs. Graphics. PPS sampling without
    replacement. Principal components, factor analysis.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
