travis:
  secure:
    BINSTAR_TOKEN: hIth9Q94OQsz0cEnRIA8eH/6HPoQ8+TsTmBcm+i09qqhnIWOoqTEGI+IYF9VYELll5xjYfIijZlpmMoq/GBBHUAxXFj6S2MvQq64ZnNMlKFbbl+tod8/apJeT7iJZ0MnqIHDaEmWfc4n+S65BFitY9whuygIMNAtd6pnV04LHLXJ4T/otxf0fwnKqBlC1yMKI3SqfKupZpsmDQiFqUsxpaldXWVdu4sgHGhilikPjC2ByZAyY3tiVLcObSip00P/kc3LxHwvyhEyneLw8Ve6pkCMryUPRjrC7Y6khb/eeJ3amLklC9xj+YpEOvx6RkS09f+76sjch5Io3Mf9D4jrJkcI6v/9o30KO0Om2s5sr+T1wzObL1f7XCncczvA0UqY87K/oG13m0RzsspYaKs9Dl9GvRF4AIs6QNEFUyheEiAmDGWrVEnPlv48hwv+u15wK4Q3IJRLxNE/Z7NZWDuut0Vf8YncL8hECQ6ps8E/ROnb2ri0Ql8Cix/3Cn4FpHemWyOORh/9Tpygqr+BNjnL6v6jI460z7M7Q/fbMzRuBtgozeth4jsPZjn+R/5fgE0bWuBasIBS1JTHI5njaLSveOdllBmq1DLzhY+B6KO2j2rNPqMtsQn/PJBktE9N8mozfkRJVU60bFoiffzduHnZ4nW4y7aOMfG0m17TuSPr7Ys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
