appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FEZ0iMpl2rzo4r+LUZviJ+kiFLEZpgMjtf0i/s4ayLZCaz9FlLEwG2iZCpdHwPRRQh5cVHhxQSVX1dkvJWb4v8GoggBJMDHBOn0Fe+h1IaSAqJhLZDL0w3smXKKof/+FQaR80/s88oztmw3mlYpqjgJMrPiIzoV5nRcQ6MtdkVBlUqZLT2qIWXKr9UATKqV+dNW3VkxmO6PhchOpvmLyEzJrhMkLYWakfVbOiA/5f1t0qGikMreVS5J6pxUAZdWsatyiZ7+RbUaITfkVPf+D9VEJrCp7K7unbQTDIASyOIpMhoQO8Tx7zCdBzCx2nbMir5ew0pRC/POLeJOcxKgl1jyDg7R6qnk3y/SQQynv461vBhDklxA7lnOuONxxeFAkHsiyamlnrnQpxQ4tevfNbAhR/UwjBIvbuGMRrcPDFH4uhV3/JZMmmjqfUZBgN4ef73TpiBsDntD5dVDunze5RYH164t3pXDJC2gPCO8AA3pXfyX8yB1evWdlen0qAsyb1h4Khda0C1N5i443Ijs8ItCYKH9IhK3O5rOz2+CYJ8M+Khs/NEgw9BrH3ar9tZpPowZL3Ph++9M1O3fcHRS7QO9L3LSXJG4ZqSPt4ZR0f4crv4/RV/PbwjmO2tbZ4hz3Mls90oZat5EW1MK3EiVRk15+7tKjApWWqJzjkNaOj5M=
conda_forge_output_validation: false
